server:
  port: 8101
spring:
  main:
    allow-circular-references: true
  application:
    name: gateway-demo
  cloud:
    nacos:
      username: nacos
      password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service-demo
        uri: http://127.0.0.1:8093
        predicates:
        - Path=/service-demo/**